### ISSUE TITLE
Add default stacks

### ISSUE THREAD

**Issue by bibendi** [bibendi/dip#1]
Add default stack files.

``` yml
stacks:
  - ruby
  - rails
  - postgres
  - mysuperstack:
      source: github.com/user/repo/path_to_mysuperstack.yml

interaction:
  services:
    app:
      stacks:
        - ruby
        - rails
      tasks:
        rebuild:
          command: dip bundle exec rake rebuild
    pg:
      stacks:
        - postgres
    superservice:
      stacks:
        - mysuperstack
```

``` sh
dip stacks install
```

It will download yml files:
- for ruby from bibendi/dip-stacks/ruby.yml
- for rails from bibendi/dip-stacks/rails.yml
- for mysuperstack from github.com/user/repo/path_to_mysuperstack.yml

And place it to `~/.dip/stacks/`

Example of ruby.yml stack:

``` yml
irb:
  command: irb
bundle:
  command: bundle
rake:
  command: bundle exec rake
```
