### ISSUE TITLE
Unable to use nginx proxy

### ISSUE THREAD

**Issue by chadwilken** [bibendi/dip#111]
First and foremost, thanks for the great tool. It makes working with docker so much more enjoyable.

**Describe the bug**
I attempt to use `dip nginx up` along with setting the `VIRTUAL_HOST`, `VIRTUAL_PATH`, and `VIRTUAL_PORT` environment variables on the `rails` service. I also added the `networks` as shown in the example for the `frontend` and `default` networks. Whenever I try to connect to the hostname I used it doesn't seem to work. I either get a `503 Service Temporarily Unavailable` response from nginx. The logs show the request if I do `curl -H "Host: companycam.local" localhost` but it doesn't actually send it to my app.

**To Reproduce**
1. Provide dip.yml config
```yaml
version: "4.1"

environment:
  RAILS_ENV: development

compose:
  files:
    - docker-compose.yml
  project_name: companycam

interaction:
  sh:
    description: Open a Bash shell within a Rails container (with dependencies up)
    service: runner
    command: /bin/bash

  bash:
    description: Open a Bash shell
    service: runner
    command: /bin/bash
    compose_run_options: [no-deps]

  guard:
    description: Run guard
    service: runner
    environment:
      RAILS_ENV: test
      KMS_KEY_ID: insecure-test-key
      GENIUS_SCAN_KEY: test-key
    command: bundle exec guard

  bundle:
    description: Run Bundler commands
    service: runner
    command: bundle

  yarn:
    description: Run Yarn commands
    service: runner
    command: yarn

  rake:
    description: Run Rake commands
    service: runner
    command: bundle exec rake

  rails:
    description: Run Rails commands
    service: runner
    command: bundle exec rails
    subcommands:
      s:
        description: Run Rails server available at http://localhost:3000
        service: rails
        compose:
          run_options: [service-ports, use-aliases]

  sidekiq:
    description: Run Sidekiq worker
    service: runner
    command: bundle exec sidekiq

  rspec:
    description: Run RSpec commands within test environment
    service: runner
    environment:
      RAILS_ENV: test
      KMS_KEY_ID: insecure-test-key
      GENIUS_SCAN_KEY: test-key
    command: bundle exec rspec

  rubocop:
    description: Lint ruby files
    service: runner
    command: bundle exec rubocop
    compose:
      run_options: [no-deps]

  dev_prime:
    description: Setup the local databases with some default data
    service: runner
    command: bundle exec rails dev:prime

  psql:
    description: Open a Postgres console
    service: postgis
    default_args: companycam_development
    command: psql -h postgis -U postgres

  mongo:
    description: Open a Mongo console
    service: mongo
    command: mongo --host mongodb://mongo:27017/companycam_development

provision:
  - dip compose down --volumes --remove-orphans
  - dip compose up -d
  - dip bundle install
  - dip yarn install
  - dip rails db:create
  - dip rails db:environment:set RAILS_ENV=${RAILS_ENV}
  - dip rails db:schema:load
  - dip rails db:migrate
  - dip rails db:create_indexes
```
2. Provide docker-compose.yml
```yaml
version: "2.4"

x-app: &app
  build:
    context: .dockerdev
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: "2.5.7"
      PG_MAJOR: "10"
      NODE_MAJOR: "10"
      YARN_VERSION: "1.22.5"
      BUNDLER_VERSION: "2.1.4"
  volumes:
    - .:/app:cached
    - bundle:/bundle
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
    NPM_TOKEN: "${NPM_TOKEN}"
    BUNDLER_VERSION: "2.1.4"
  image: companycam-dev:0.0.1
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
  environment:
    <<: *env
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    MALLOC_ARENA_MAX: 2
    WEB_CONCURRENCY: ${WEB_CONCURRENCY:-2}
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: vim
    REDIS_URL: redis://redis:6379/0
    KMS_KEY_ID: ${KMS_KEY_ID}
    SIDEKIQ_REDIS_URL: redis://redis:6379/1
    REDIS_OBJECTS_URL: redis://redis:6379/2
    SEARCHKICK_REDIS_URL: redis://redis:6379/3
    RACK_THROTTLE_REDIS_URL: redis://redis:6379/4
    GRAPHQL_REDIS_URL: redis://redis:6379/5
    DATABASE_URL: postgres://postgres:postgres@postgis:5432/companycam_${RAILS_ENV:-development}
    EVENTS_DATABASE_URL: postgres://postgres:postgres@postgis:5432/events_${RAILS_ENV:-development}
    MONGO_URL: "mongodb://mongo:27017/companycam_${RAILS_ENV:-development}"
    ELASTICSEARCH_URL: http://elasticsearch:9200
    VIRTUAL_HOST: '*.companycam.local'
    VIRTUAL_PATH: '/'
    VIRTUAL_PORT: '3000'
  depends_on:
    postgis:
      condition: service_healthy
    redis:
      condition: service_started
    memcached:
      condition: service_started
    mongo:
      condition: service_healthy
    elasticsearch:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - "3002:3002"

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    networks:
      - default
      - frontend
    dns: $DIP_DNS

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      BOOTSNAP_CACHE_DIR: /bundle/bootsnap

  postgis:
    image: mdillon/postgis:10
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgis:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: companycam_development
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1 -d companycam_development
      interval: 5s

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: companycam_development
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/companycam_development --quiet
      interval: 5s

  memcached:
    image: memcached
    ports:
      - "11211"
    healthcheck:
      disable: true
    #   test: memcached-tool 127.0.0.1:11211 stats
    #   interval: 3s
    #   timeout: 3s
    #   retries: 30

  redis:
    image: redis:5.0-alpine
    ports:
      - 6379
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cat/health"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgis:
  mongodb:
  redis:
  elasticsearch:
  bundle:
  node_modules:
  rails_cache:
  packs:

networks:
  frontend:
    external:
      name: frontend
```
3. Run command
- `dip ngnix up`
- `dip rails s`

**Expected behavior**
I am able to connect to companycam.local and see the app.

**Context (please complete the following information):**
 - OS: MacOS Catalina
 - Version 6.1.0

**Additional Context**
I am running puma-dev presently as we are preparing for the docker switch. I believe that runs on port 80, so not sure if that would conflict since it seems that nginx is receiving the request.
