### ISSUE TITLE
Dip does not wrap an actual container command in quotes on Ubuntu

### ISSUE THREAD

**Issue by snthpr1d3** [bibendi/dip#132]
First of all, thank you for the really great, useful and handy tool. I apologize in advance for possible grammar mistakes. Also, I assume I might misunderstand the actual reason of the issue.

**Describe the bug**
It's impossible to use a container application with arguments on Ubuntu and therefore it's impossible to use advanced shell constructions.

**To Reproduce**
1. Create any folder, e.g. `/tmp/test_project`
2. Create the `dip.yml` config file in the folder:
```yaml
version: '2'

compose:
  files:
    - docker-compose.yml
 
 interaction:
    bash:
      service: test
      command: /bin/sh

provision:
  - dip bash -c  'if [[ true ]]; then echo works; fi'
```
3. Create the `docker-compose.yml` config file in the folder:
```yaml
version: '3.5'

services:
  test:
    image: alpine
    command: tail -f /dev/null
```
4. Run command `dip provision` or `dip bash -c 'if [[ true ]]; then echo works; fi'` from the folder.
4. See the error
```
sh: -c: line 1: syntax error near unexpected token `then'
sh: -c: line 1: `docker-compose --file /home/snthpr1d3/work/dip_bug/docker-compose.yml run --rm test /bin/sh -c if [[ true ]]; then echo works; fi'
ERROR: Command 'dip bash -c  'if [[ true ]]; then echo works; fi'' executed with error
```

**Expected behavior**
Performs the shell command correctly and prints "works" as on MacOS environment.

**Context (please complete the following information):**
 - OS: Ubuntu 21.04
 - Version 7.1.0

**Additional context**
Don't reproduce on MacOS environment.

As you can see the `dip bash -c 'if [[ true ]]; then echo works; fi` sample command transcripts into 

```docker-compose --file /home/snthpr1d3/work/dip_bug/docker-compose.yml run --rm test /bin/sh -c if [[ true ]]; then echo works; fi```

which is evidently requires quotes to surround the arguments like this

```docker-compose --file /home/snthpr1d3/work/dip_bug/docker-compose.yml run --rm test /bin/sh -c 'if [[ true ]]; then echo works; fi'```

as it was in the original config file: `dip bash -c  'if [[ true ]]; then echo works; fi'`

As I mentioned before, works correctly on MacOS.
