### ISSUE TITLE
Can I use more than one provision or there have another way to run commands each by each？

### ISSUE THREAD

**Issue by Dearest** [bibendi/dip#143]
I have some requirements, I want to use one command to execute multiple interactions
For example I have a dip.yml like this
```yml
interaction:
  rails:
    description: Run Rails commands
    service: rails
    command: bundle exec rails
    subcommands:
      s:
        description: Run Rails server 
        service: rails
        compose:
          run_options: [service-ports, use-aliases]

  yarn:
    description: Run Yarn commands
    service: rails
    command: yarn
    compose_run_options: [no-deps]
```

I want to use one command like `dip start-server`。It can run like provision to run
```yml
- dip rails s
- dip yarn start
```

Can I make it happen?

**Comment by Dearest** [comment]
@bibendi   Can I make a pull request to implement this feature?
maybe I will add a keyword like `flow`。 it will have the same level as `interaction ` or `provision `。
`flow` is very similar to `provision`, but it can define multiple。
maybe it look like this
```yml
interaction:
  rails:
    description: Run Rails commands
    service: rails
    command: bundle exec rails
    subcommands:
      s:
        description: Run Rails server 
        service: rails
        compose:
          run_options: [service-ports, use-aliases]

  yarn:
    description: Run Yarn commands
    service: rails
    command: yarn
    compose_run_options: [no-deps]

flow:
  start:
    - rails s
    - yarn start
```

I can use `dip flow start` to run `rails s` and `yarn start` one by one
