### ISSUE TITLE
Allow to run app with port mapping

### ISSUE THREAD

**Issue by artofhuman** [bibendi/dip#16]
For example, I have compose file:
```
› cat docker-compose.yml
version: '2'

services:
  web:
    build: '.'
    command: 'bash -c "bundle exec hanami server -p 3000 --host 0.0.0.0"'
    environment:
      - SSH_AUTH_SOCK=/ssh/auth/sock
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - ssh-data:/ssh:ro
    depends_on:
      - db
```

and dip.yml
```yml
...

  hanami:
    service: web

    subcommands:
      server:
        service: web
```

If i run server through dip:
` DIP_DEBUG=1 dip hanami server`
```
"docker-compose --file docker-compose.yml --project-name auto run -e HANAMI_ENV=development --rm web"
```
```
b1596b2a4c43        auto                            "bash -c 'bundle exec"   2 days ago          Up 2 seconds        3000/tcp                     auto_web_run_1
```

Port mapping not work.
For simple applications which don't use dns we should allow run app server with port mapping.
compose command should be with `--service-ports`

```
docker-compose --file docker-compose.yml --project-name auto run -e HANAMI_ENV=development --service-ports --rm web
```
```
4c90c609da55        auto                            "bash -c 'bundle exec"   2 days ago          Up 4 seconds        0.0.0.0:3000->3000/tcp       auto_web_run_1
```

maybe we should use special option in dip.yml `ports: true`?
```yml
hanami
  service: web
  
   subcommands:
     server:
       service: web
       ports: true
```

What do u think?

**Comment by deniskorobicyn** [comment]
What if we call it same way as in compose - 
```yaml
hanami
  service: web
  
   subcommands:
     server:
       service: web
       service_ports: true
```
?

**Comment by artofhuman** [comment]
I think about another way to pass any args, it can be useful

```yml
hanami
  service: web
  
   subcommands:
     server:
       service: web
       compose_run_args:
          - service-ports
          - no-deps
```
