### ISSUE TITLE
Run command with env variable

### ISSUE THREAD

**Issue by artofhuman** [bibendi/dip#5]
For example in case below BUNDLE_VERSION in command is empty
```
# dip.yml

environment:
   BUNDLE_VERSION: 1.12.5

interaction:
  rspec:
    service: app
    command: bundle exec appraisal bundle _${BUNDLE_VERSION}_ exec rspec
```
