### ISSUE TITLE
environment configuration is not working

### ISSUE THREAD

**Issue by palkan** [bibendi/dip#62]
**Version**: 3.8.2 (MacOS binary).

Environment variables specified under `interaction -> [service] -> environment` are not passed to container.

Example:

```yml
interaction:
  service: app
  environment:
    SAMPLE: 42
  command: echo
```

Expected:

```sh
$ dip echo $SAMPLE
42
```

Actual:

```sh
$ dip echo $SAMPLE


```

**Comment by bibendi** [comment]
I think you don't throw this variable through docker-compose service. You should have something like this:

```
docker-compose.yml
services:
  app:
    environment:
      - SAMPLE=${SAMPLE}
```

The environment section in a dip.yml is changing environment variables on the host machine only.
