### ISSUE TITLE
Rails logger, bybug

### ISSUE THREAD

**Issue by dixpac** [bibendi/dip#80]
Hi!

Awesome project! Trying to set it up on my rails 6 app. Everything works fine except when I try to debug with `byebug or pry` and when I try to write something to the logs ex; `puts "lol" * 100` nothing happens.

Am I missing some configuration steps to make this work?

Thanks

**Comment by bibendi** [comment]
Hi!

Can you give your docker-compose.yml and dip.yml?

**Comment by dixpac** [comment]
@bibendi  ah sorry I should attach my docker-compose and dip when opening issue :)

docker-compose
```
version: '2.4'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
      args:
        RUBY_VERSION: '2.6.5'
        PG_MAJOR: '11'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.19.1'
        BUNDLER_VERSION: '2.0.2'
    image: fhirwire-dev:1.0.0
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3000:3000'
      - '3002:3002'

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'

  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgres:
    image: postgres:10.10
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
```

dip.yml
```
version: '4.1'

environment:
  RAILS_ENV: development

compose:
  files:
    - docker-compose.yml

interaction:
  sh:
    description: Open a Bash shell within a Rails container (with dependencies up)
    service: backend
    command: /bin/bash

  bash:
    description: Run an arbitrary script within a container (or open a shell without deps)
    service: backend
    command: /bin/bash
    compose_run_options: [no-deps]

  bundle:
    description: Run Bundler commands
    service: backend
    command: bundle
    compose_run_options: [no-deps]

  rake:
    description: Run Rake commands
    service: backend
    command: bundle exec rake

  rails:
    description: Run Rails commands
    service: backend
    command: bundle exec rails
    subcommands:
      s:
        description: Run Rails server available at http://localhost:3000
        service: rails
        compose:
          run_options: [service-ports, use-aliases]

  'run-tests':
    description: Run mini-test commands within test environment
    service: backend
    environment:
      RAILS_ENV: test
    command: bundle exec rails test

  'run-tests:system':
    description: Run mini-test commands within test environment
    service: backend
    environment:
      RAILS_ENV: test
    command: bundle exec rails test:system

  rubocop:
    service: backend
    command: bundle exec rubocop
    compose_run_options: [no-deps]

  yarn:
    service: backend
    command: yarn
    compose_run_options: [no-deps]

  psql:
    service: postgres
    command: psql -h postgres -U postgres -d fhirwire_development

  'redis-cli':
    service: redis
    command: redis-cli -h redis

provision:
  - dip compose down --volumes
  - dip compose up -d postgres redis
  - dip bundle install
  - dip yarn install
  - dip rails db:create
  - dip rails db:migrate
```
