### ISSUE TITLE
Question: How can I provide arguments to `dip compose`?

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [bibendi/dip#90]
Hey all,

First, thank you for building this helpful tool that makes my life a bit easier. Second, my apologies for asking this question as Github issue - I didn't know if I should go pester people on Twitter or not 😄 .

I'd like to automatically provide arguments to `dip compose` - specifically, I'd like to have the flags set true for Docker's `buildkit` commands: `COMPOSE_DOCKER_CLI_BUILD=1` and `DOCKER_BUILDKIT=1`. That way, whenever I run `dip compose build`, it will automatically add `DOCKER_BUILDKIT=1`.

Thanks for any and all help.

**Comment by bibendi** [comment]
Hi Kurt 🤝 

Right now you cannot do that.

As far as I remember the buildkit is available only on the latest Docker version. I think it would be unfair to the users on older Docker because they cannot build an image.

**Comment by kurt-mueller-osumc** [comment]
Fair enough. Feature request 😁  - allow me to add args.

```yaml
compose:
  files:
    - docker/docker-compose.yml
    - docker/docker-compose.$COMPOSE_EXT.yml
    - docker/docker-compose.$DIP_OS.yml
  project_name: bear
  args:
    - DOCKER_BUILDKIT=1
    - COMPOSE_DOCKER_CLI_BUILD=1
```

Something along those lines.
