### ISSUE TITLE
How do I restart just the rails app?

### ISSUE THREAD

**Issue by timuckun** [bibendi/dip#93]
I don't want to stop the posgres and such, just want to kick the rails process. 

The rails service has a dependency on postgres so that adds a layer of complexity as well.

Thanks.

**Comment by bibendi** [comment]
How do you start it?
If your dip.yml config looks like below

```yaml
  rails:
    description: Run Rails commands
    service: rails
    command: bundle exec rails
    subcommands:
      s:
        description: Run Rails server available at http://localhost:3000
        command: bundle exec rails server -b 0.0.0.0
        compose:
          run_options: [service-ports, use-aliases]
```

I suppose you start Rails like `dip rails s`
So, to stop it you need just press `ctrl + c` :)

**Comment by milushov** [comment]
@bibendi what if I start my project with `dip up -d`? How to restart only rails?

```
interaction:
  ...
  rails:
    service: backend
    command: bundle exec rails
    subcommands:
      s:
        service: backend
        compose_run_options: [service-ports]
```

btw thanks for awesome work, my colleague revealed me this gem yesterday and I'm super happy!
